### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by computerAItest** [zhangzhehao95/CNN-MoCo#2]
When I train the model, I get this error
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    main()
  File "main.py", line 48, in main
    train_dataset, val_dataset, test_dataset, pred_dataset = Dataset_Generator().make(cf)
  File "/home/yp/CNN-MoCo-main/CNN-MoCo-main/artifact_reduction_CNN/dataset/dataset_generator.py", line 25, in make
    flag='train')
  File "/home/yp/CNN-MoCo-main/CNN-MoCo-main/artifact_reduction_CNN/dataset/tf_dataset.py", line 131, in tfDataset
    images_ds = images_ds.shuffle(buffer_size=buf_size, reshuffle_each_iteration=True)
  File "/home/yp/anaconda3/envs/python37/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1624, in shuffle
    self, buffer_size, seed, reshuffle_each_iteration, name=name)
  File "/home/yp/anaconda3/envs/python37/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 5125, in __init__
    **self._common_args)
  File "/home/yp/anaconda3/envs/python37/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 7345, in shuffle_dataset_v3
    _ops.raise_from_not_ok_status(e, name)
  File "/home/yp/anaconda3/envs/python37/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__ShuffleDatasetV3_device_/job:localhost/replica:0/task:0/device:CPU:0}} buffer_size must be greater than zero. [Op:ShuffleDatasetV3]

**Comment by zhangzhehao95** [comment]
Hi,

The error here seems like your buffer size is not suitable. Could you double check whether you have successfully loaded the training data to the TensorFlow Dataset class? 

In the provided data loading file (tf_dataset.py), the varibale for buffer size, 'buf_size', is set as the amount of patches divided by two. Although it will be ideal to set it equal to the size of training data, the choice here is just to speed up the shuffling process. Please feel free to adjust this variable (greater than zero) to see whether you can fix this error.

Best,
Zhehao
